---
title: 'BariatricPal Hospital MX: Bariatric & Plastic Surgery in Mexico'
timezone: UTC
collections:
  packages:
    title: Packages
    output: true
  plastic-surgeries:
    title: Plastic Surgeries
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  weight-loss-surgeries:
    title: Weight Loss Surgeries
    output: true
defaults:
- scope:
    path: ''
    type: plastic-surgeries
  values:
    layout: surgery
    seo:
      title: ''
      description: ''
    twitter:
      image: 'upload size: 120x120'
    facebook:
      image: 'upload size: 600x315'
    surgery_types:
    - description: Fill in description
      price: "$0.00"
- scope:
    path: ''
    type: weight-loss-surgeries
  values:
    layout: surgery
    seo:
      title: ''
      description: ''
    twitter:
      image: 'upload size: 120x120'
    facebook:
      image: 'upload size: 600x315'
    surgery_types:
    - description: Fill in description
      price: "$0.00"
- scope:
    path: ''
    type: packages
  values:
    layout: default
- scope:
    path: ''
    type: pages
  values:
    layout: page
    seo:
      title: ''
      description: ''
    twitter:
      image: 'upload size: 120x120'
    facebook:
      image: 'upload size: 600x315'
permalink: pretty
assetpath: "/assets/"
exclude:
- ".assets-cache"
- ".sass-cache"
- ".gitignore"
- README*
- Gemfile
- Gemfile.lock
- bower.json
- bower_components
- package.json
- node_modules
- gulpfile.js
description: For over 14 years, the BariatricPal team has been committed and completely
  dedicated to helping weight loss surgery and plastic surgery patients just like
  you.
twitter:
  image: 'upload size: 120x120'
facebook:
  image: 'upload size: 600x315'
copyright: "© Copyright current_year BariatricPal MX LLC."
menu:
  wls: BariatricPal Hospital MX's patient care team goes above and beyond anyone else.
  plastics: BariatricPal Hospital MX's patient care team goes above and beyond anyone
    else.
  testimonials: Hear what satisfied patients say about BariatricPal Hospital MX and
    Staff
analytics: |-
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-39899338-5"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'UA-39899338-5');
  </script>
