---
title: BariatricPal Hospital MX
timezone: UTC
collections:
  plastic-surgeries:
    title: Plastic Surgeries
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  weight-loss-surgeries:
    title: Weight Loss Surgeries
    output: true
defaults:
- scope:
    path: ''
    type: plastic-surgeries
  values:
    layout: surgery
    seo:
      title: ''
      keywords: ''
      description: ''
    twitter:
      image: 'upload size: 120x120'
    facebook:
      image: 'upload size: 600x315'
    surgery_types:
    - description: Fill in description
      price: "$0.00"
- scope:
    path: ''
    type: weight-loss-surgeries
  values:
    layout: surgery
    seo:
      title: ''
      keywords: ''
      description: ''
    twitter:
      image: 'upload size: 120x120'
    facebook:
      image: 'upload size: 600x315'
    surgery_types:
    - description: Fill in description
      price: "$0.00"
- scope:
    path: ''
    type: pages
  values:
    layout: page
    seo:
      title: ''
      keywords: ''
      description: ''
    twitter:
      image: 'upload size: 120x120'
    facebook:
      image: 'upload size: 600x315'
permalink: pretty
assetpath: "/assets/"
exclude:
- ".assets-cache"
- ".sass-cache"
- ".gitignore"
- README*
- Gemfile
- Gemfile.lock
- bower.json
- bower_components
- package.json
- node_modules
- gulpfile.js
description: BariatricPal has a long and impressive history. For over 14 years, the
  BariatricPal team has been committed and completely dedicated to helping patients
  just like you.
keywords: weight loss surgeons surgeries plastic surgery plastics bariatric all-inclusive
  hospital Mexico 5-stars
copyright: "© Copyright current_year BariatricPal MX LLC."
menu:
  wls: BariatricPal Hospital MX's patient care team goes above and beyond anyone else.
  plastics: BariatricPal Hospital MX's patient care team goes above and beyond anyone
    else.
  testimonials: Hear what satisfied patients say about BariatricPal Hospital MX and
    Staff
