---
title: 'BariatricPal Hospital MX: Bariatric & Plastic Surgery in Mexico'
timezone: UTC
collections:
  packages:
    title: Packages
    output: true
  plastic-surgeries:
    title: Plastic Surgeries
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  weight-loss-surgeries:
    title: Weight Loss Surgeries
    output: true
defaults:
- scope:
    path: ''
    type: plastic-surgeries
  values:
    layout: surgery
    seo:
      title: ''
      description: ''
    twitter:
      image: 'upload size: 120x120'
    facebook:
      image: 'upload size: 600x315'
    surgery_types:
    - description: Fill in description
      price: "$0.00"
- scope:
    path: ''
    type: weight-loss-surgeries
  values:
    layout: surgery
    seo:
      title: ''
      description: ''
    twitter:
      image: 'upload size: 120x120'
    facebook:
      image: 'upload size: 600x315'
    surgery_types:
    - description: Fill in description
      price: "$0.00"
- scope:
    path: ''
    type: packages
  values:
    layout: default
- scope:
    path: ''
    type: pages
  values:
    layout: page
    seo:
      title: ''
      description: ''
    twitter:
      image: 'upload size: 120x120'
    facebook:
      image: 'upload size: 600x315'
permalink: pretty
assetpath: "/assets/"
exclude:
- ".assets-cache"
- ".sass-cache"
- ".gitignore"
- README*
- Gemfile
- Gemfile.lock
- bower.json
- bower_components
- package.json
- node_modules
- gulpfile.js
description: 'The Most Experienced Bariatric & Plastic Surgeons in Mexico. Feel comfortable
  with our internationally recognized surgical experts in laparoscopic surgery and
  reconstructive procedures. '
twitter:
  image: 'upload size: 120x120'
facebook:
  image: 'upload size: 600x315'
copyright: "© Copyright current_year BariatricPal MX LLC."
menu:
  wls: BariatricPal Hospital MX's patient care team goes above and beyond anyone else.
  plastics: BariatricPal Hospital MX's patient care team goes above and beyond anyone
    else.
  testimonials: Hear what satisfied patients say about BariatricPal Hospital MX and
    Staff
analytics: |-
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-39899338-5"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'UA-39899338-5');
  </script>
pixel: "<!-- Facebook Pixel Code -->\n<script>\n!function(f,b,e,v,n,t,s)\n{if(f.fbq)return;n=f.fbq=function(){n.callMethod?\nn.callMethod.apply(n,arguments):n.queue.push(arguments)};\nif(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';\nn.queue=[];t=b.createElement(e);t.async=!0;\nt.src=v;s=b.getElementsByTagName(e)[0];\ns.parentNode.insertBefore(t,s)}(window,document,'script',\n'https://connect.facebook.net/en_US/fbevents.js');\n
  fbq('init', '130121717445691'); \nfbq('track', 'PageView');\n</script>\n<noscript>\n
  <img height=\"1\" width=\"1\" \nsrc=\"https://www.facebook.com/tr?id=130121717445691&ev=PageView\n&noscript=1\"/>\n</noscript>\n<!--
  End Facebook Pixel Code -->"
